config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    session: 'admin/session'
  }
  resources :users
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about
    @about_me = "My first RubyOnRails project...!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :correct_admin, only: [:edit, :update, :destroy]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    # @user = User.new
    @user = current_admin.users.build
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def correct_admin
    @user = current_admin.users.find_by(id: params[:id])
    redirect_to users_path, notice: "Not Authorized To Edit This Friend" if @user.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<nav class="nav">
  <div class="card-footer text-muted" style="text-align: center">
    RubyOnRailsRB
  </div>
</nav>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if admin_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#"><%= link_to 'Users', users_path, class: "nav-link" %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><%= link_to 'Add User', new_user_path, class: "nav-link" %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><%= link_to 'Sign Out', destroy_admin_session_path, data: { turbo_method: :delete }, class: "nav-link" %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><%= link_to 'Edit Profile', edit_admin_registration_path, class: "nav-link" %></a>
          </li>

        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="#"><%= link_to 'Sign Up', new_admin_registration_path, class: "nav-link" %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><%= link_to 'Sign In', new_admin_session_path, class: "nav-link" %></a>
          </li>

        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= link_to 'About Us', home_about_path, class: "nav-link" %></a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us!</h1>

<p>
  <%= @about_me %>
</p>

app/views/home/index.html.erb
<h1>Hello World!!!</h1>
Hi.

app/views/layouts/_alerts.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Friends</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<div class="container">
  <br/>
  <%= render 'home/header' %>
  <%if notice%>
  <%= render 'layouts/alerts'%>
  <% end%>
  <br/>
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
<footer>

</footer>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :twitter, class: "form-control", placeholder: "Twitter" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.number_field :admin_id, id: :user_admin_id, class: "form-control", value: current_admin.id, type: :hidden %>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>
  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>
  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>
  <p>
    <strong>Twitter:</strong>
    <%= user.twitter %>
  </p>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user, class: "btn btn-secondary" %> |
  <%= link_to "Back to users", users_path, class: "btn btn-secondary" %>
</div>

app/views/users/index.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Email</th>
    <th scope="col">Phone</th>
    <th scope="col">Twitter</th>
    <th colspan="2"></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <% if user.admin == current_admin %>
      <tr>
        <td></td>
        <td><%= link_to user.first_name +  " " + user.last_name, user, class: "btn", style: "color: Blue" %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.twitter %></td>
        <div>
            <%#= link_to 'Show', user, class: "btn btn-primary" %>
          <td style="padding: 0px;">
            <%= link_to 'Edit', edit_user_path(user), class: "btn btn-secondary mt-1" %>
          </td>
          <td style="padding: 0px;">
            <%= button_to 'Delete', user, method: :delete, class: "btn btn-danger mt-1" %>
          </td>
        </div>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Add User</h1>
<br/>
<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path, class: "btn btn-dark" %>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @user.first_name %> <%= @user.last_name %></h1>
  <p class="lead"><%= @user.email %></p>
  <hr class="my-4">
  <p><%= @user.phone %></p>
  <p>Twitter: <%= @user.twitter %></p>
  <%= link_to "Edit", edit_user_path(@user), class: "btn btn-secondary" %>
  <%= link_to "Back", users_path, class: "btn btn-secondary" %>

</div>